# Generated by Django 4.2.10 on 2024-03-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_foreign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='foreign',
            new_name='foreignkey',
        ),
    ]
