# Generated by Django 4.2.10 on 2024-03-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_foreign_userprofile_foreignkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_auth_extended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='userProfile',
        ),
    ]
