# Generated by Django 4.2.10 on 2024-03-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_auth_extended_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_pos_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=255, unique=True)),
                ('merchant_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('number_of_pos_requested', models.IntegerField()),
                ('document_name_1', models.BooleanField(default=False)),
                ('document_name_2', models.BooleanField(default=False)),
                ('document_name_3', models.BooleanField(default=False)),
                ('document_name_4', models.BooleanField(default=False)),
                ('document_name_5', models.BooleanField(default=False)),
                ('currency', models.CharField(max_length=255)),
                ('ownership_type', models.CharField(max_length=255)),
                ('set_up_fee', models.IntegerField()),
                ('date_requested', models.DateTimeField()),
                ('remarks', models.TextField()),
            ],
        ),
    ]
