# Generated by Django 4.2.10 on 2024-03-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_new_pos_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='merchant_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(max_length=255)),
                ('rsm', models.CharField(max_length=255)),
                ('office_address', models.CharField(max_length=255)),
                ('postal_address', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('nature_of_business', models.CharField(max_length=255)),
                ('contact_person', models.IntegerField(max_length=12)),
                ('settlement_account_number', models.IntegerField(max_length=20)),
                ('scheme_platform', models.CharField(max_length=255)),
                ('commissions', models.IntegerField(max_length=255)),
                ('settlement_period', models.CharField(max_length=255)),
            ],
        ),
    ]
