# Generated by Django 4.2.10 on 2024-03-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merchant_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='pos_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_name', models.CharField(max_length=255)),
                ('pos_id', models.CharField(max_length=255)),
                ('pos_brand', models.CharField(max_length=255)),
                ('pos_serial_number', models.CharField(max_length=255)),
                ('pos_model', models.CharField(max_length=255)),
                ('pos_collection_account_number', models.CharField(max_length=20)),
                ('sim_serial_number', models.CharField(max_length=255)),
                ('deployed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='merchant_information',
            name='business_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
