# Generated by Django 4.2.10 on 2024-03-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pos_information_merchant_information_business_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.IntegerField(max_length=255, unique=True)),
                ('division', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
            ],
        ),
    ]
