# Generated by Django 4.2.10 on 2024-03-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_branches'),
    ]

    operations = [
        migrations.CreateModel(
            name='pos_deployment_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=255)),
                ('pos_id', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('branch_code', models.IntegerField(max_length=255)),
                ('rsm', models.CharField(max_length=255)),
                ('location_deployed_to', models.CharField(max_length=255)),
                ('period_of_inactivity', models.DateTimeField()),
                ('period_of_activity', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('date_of_deployment', models.CharField(max_length=255)),
                ('date_of_retrieval', models.CharField(max_length=255)),
                ('last_date_of_transaction', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='user_auth_extended',
            name='role',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pos_information',
            name='pos_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
