# Generated by Django 4.2.10 on 2024-03-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pos_deployment_report_user_auth_extended_role_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_auth_extended',
            new_name='auth_user_extended',
        ),
    ]
