# Generated by Django 4.2.10 on 2024-03-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_user_auth_extended_auth_user_extended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auth_user_extended',
            old_name='email',
            new_name='username',
        ),
    ]
