# Generated by Django 4.2.10 on 2024-03-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_email_auth_user_extended_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_user_extended',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
