# Generated by Django 4.2.10 on 2024-03-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_auth_user_extended_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth_user_extended',
            name='department',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
