# Generated by Django 4.2.10 on 2024-03-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auth_user_extended_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='auth_user_extended',
            new_name='profile_extended',
        ),
    ]
