# Generated by Django 4.2.10 on 2024-03-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_auth_user_extended_profile_extended'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos_information',
            name='sim_network_type',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pos_information',
            name='pos_serial_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
